### PR TITLE
Use remote docker for builds

### PR DESCRIPTION
**Pull request by SuperQ**
Use CircleCI remote docker for builds rather than machine mode.

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by discordianfish** [comment]
That won't work with #19 though

**Comment by SuperQ** [comment]
I think it will make #19 easier.

**Comment by discordianfish** [comment]
I'm confused. How so? #19 uses local machine, so if we merge this here it will get overwritten anyway..?

**Comment by SuperQ** [comment]
@discordianfish, @johanneswuerbach Rebased on top of #19 and #21, PTAL

**Comment by johanneswuerbach** [comment]
Nice 👏 , could you also try to remove this line? https://github.com/prometheus/busybox/blob/master/.circleci/config.yml#L20

**Comment by johanneswuerbach** [comment]
I assume the still modify the remote docker executor, but if this works 👌🚀

**Comment by discordianfish** [comment]
Interesting! Well then..

**Pull request merged**
