### PR TITLE
Rewrote cross-arch support

### PR DESCRIPTION
**Pull request by johanneswuerbach**
Publish image archs to respective repositories named after `GOOS` and `GOARCH`

Publish a manifest to `prom/busybox` so pulling `docker pull prom/busybox:latest` still works and automatically resolves the correct arch.

### CODE REVIEW

**Comment by SuperQ** [comment]
Yea, I like this much more, the consistency helps.

**Comment by johanneswuerbach** [comment]
Just to be clear, this also means we now need 4 `busybox-linux-{arch}` repositories here per registry and the one `busybox` to hold the manifests.

**Comment by SuperQ** [comment]
Yes, I can create those registries.

We also need to remove the old multi-arch ones to avoid users using outdated packages. I wonder if it's possible to rename and automatically redirect users to the new one.

**Comment by johanneswuerbach** [comment]
@SuperQ sorry, I have no idea whether docker hub is doing redirects. At least in my personal repositories, there seems to be no rename option :-(

**Comment by SuperQ** [comment]
Yea, I looked, there is no rename or redirect option. :frowning_face:

**Comment by SuperQ** [comment]
Ok, I've created all the repos.

**Comment by johanneswuerbach** [comment]
@SuperQ looks like there is something missing:

```
The push refers to a repository [quay.io/prometheus/busybox-linux-amd64]


unauthorized: access to the requested resource is not authorized
Makefile:60: recipe for target 'push' failed
```

**Comment by SuperQ** [comment]
Yea, I had the wrong bot permissions. Re-running now.

**Comment by SuperQ** [comment]
Hrm, it failed with a different error now:
```console
# Manifest for "ulibc"
DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create -a "quay.io/prometheus/busybox:uclibc" \
	"quay.io/prometheus/busybox-linux-amd64:uclibc" \
	"quay.io/prometheus/busybox-linux-armv7:uclibc" \
	"quay.io/prometheus/busybox-linux-armv8:uclibc"
unsupported manifest media type and no default available: application/vnd.docker.distribution.manifest.v1+prettyjws
Makefile:36: recipe for target 'manifest' failed
make: *** [manifest] Error 1
```

**Pull request merged**
