### PR TITLE
Use arm64 instead of armv8

### PR DESCRIPTION
**Pull request by johanneswuerbach**
The go arch of armv8 is arm64

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
@simonpasquier I pushed this now to "my" registry and I can't reproduce the amd64 only problem.

Using:

```
REPOSITORY=johanneswuerbach SUFFIX="" make build tag push manifest
```

I get the following:

https://cloud.docker.com/repository/registry-1.docker.io/johanneswuerbach/busybox/tags
image

**Comment by johanneswuerbach** [comment]
@simonpasquier https://github.com/docker/cli/pull/1156/files might be the culprit, which is lucky fixed in 18.06.0, which is also the most recent version available on circle.

@SuperQ this should hopefully be the last change before the we can attempt finishing multi-arch in main prometheus/prometheus.

**Comment by SuperQ** [comment]
I'll create the new repos so this can be merged.

**Comment by johanneswuerbach** [comment]
image
❤️ upgrading docker seems to have resolved this 👏

**Comment by SuperQ** [comment]
Woot!

**Comment by simonpasquier** [comment]
Yeah! Thanks a lot @johanneswuerbach

**Pull request merged**
